# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

declare HOMEBREW_PATH
case $(uname -m); in 
  arm64)
    HOMEBREW_PATH="/opt/homebrew"
    ;;
  x86_64)
    HOMEBREW_PATH="/usr/local"
    ;;
esac

fpath=($HOMEBREW_PATH/share/zsh/site-functions/ $HOMEBREW_PATH/share/zsh-completions $fpath)
autoload -Uz compinit && compinit

source $HOMEBREW_PATH/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

groot() {
  cd "$(git rev-parse --show-toplevel)"
}

source ~/.powerlevel10k/powerlevel10k.zsh-theme
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

alias ls="lsd"
alias ll="ls -l"
alias la="ls -A"
alias lal="ls -Al"
alias lla="ls -lA"

alias cat="bat"
alias man="batman"
alias vi="nvim"

eval "$(zoxide init zsh)"

